### ISSUE TITLE
Session destroyed after reloading page

### ISSUE THREAD

**Issue by huuthotn01** [barisates/react-session-api#1]
Session should stay even when reloading page, and will be removed only when the browser is closed. In this package session is destroyed when reloading page. Anyone can help me to fix this problem?

**Comment by deepc0py** [comment]
I believe if you set useBrowserStorage it'll save the session to the browser to be used across refreshes but I'm unsure on how to update the config.

**Comment by barisates** [comment]
> I believe if you set useBrowserStorage it'll save the session to the browser to be used across refreshes but I'm unsure on how to update the config.

Yes, if you update this property to "true", the data will be kept until the browser is closed.

Class Component;

` componentDidMount() {
   Session.config(true, 0);
  }`

Function Component;

`  useEffect(() => {
     Session.config(true, 0);
  }, []);`

**Comment by deepc0py** [comment]
Thank you!
